const anillos = [
    {
        category:"Anillos",
        id:"1",
        title:"Anillo Brujula Vikinga",
        price:"650",
        image:"../anillos/anillo-brujula-vikinga-1.webp",
        image2:"../anillos/anillo-brujula-vikinga-2.webp",
    },
    {
        category:"Anillos",
        id:"2",
        title:"Anillo Garra Oso",
        price:"650",
        image:"../anillos/anillo-oso-1.webp",
        image2:"../anillos/anillo-oso-2.webp",
        image3:"../anillos/anillo-oso-3.webp",
    },
    {
        category:"Anillos",
        id:"3",
        title:"Anillo Vegvisir",
        price:"650",
        image:"../anillos/anillo-vegvisir-1.webp",
        image2:"../anillos/anillo-vegvisir-2.webp",
        image3:"../anillos/anillo-vegvisir-3.webp",
    },
    {
        category:"Anillos",
        id:"4",
        title:"Anillo Runas Slim",
        price:"650",
        image:"../anillos/anillo-runas-slim-1.webp",
        image2:"../anillos/anillo-runas-slim-2.webp",
        image3:"../anillos/anillo-runas-slim-3.webp",
        image4:"../anillos/anillo-runas-slim-4.webp",
    },
    {
        category:"Anillos",
        id:"5",
        title:"Anillo Casco Loki",
        price:"650",
        image:"../anillos/anillo-casco-loki-1.webp",
        image2:"../anillos/anillo-casco-loki-2.webp",
        image3:"../anillos/anillo-casco-loki-3.webp",
        image4:"../anillos/anillo-casco-loki-4.webp",
    },
    {
        category:"Anillos",
        id:"6",
        title:"Anillo Craneo Cabra",
        price:"650",
        image:"../anillos/anillo-craneo-cabra-1.webp",
        image2:"../anillos/anillo-craneo-cabra-2.webp",
        image3:"../anillos/anillo-craneo-cabra-3.webp",
        image4:"../anillos/anillo-craneo-cabra-4.webp",
        image5:"../anillos/anillo-craneo-cabra-5.webp",
    },
    {
        category:"Anillos",
        id:"7",
        title:"Anillo Fenrir",
        price:"650",
        image:"../anillos/anillo-fenrir-1.webp",
        image2:"../anillos/anillo-fenrir-2.webp",
        image3:"../anillos/anillo-fenrir-3.webp",
    },
    {
        category:"Anillos",
        id:"8",
        title:"Anillo Hugin & Munin",
        price:"650",
        image:"../anillos/anillo-hugin-munin-1.webp",
        image2:"../anillos/anillo-hugin-munin-2.webp",
        image3:"../anillos/anillo-hugin-munin-3.webp",
    },
    {
        category:"Anillos",
        id:"9",
        title:"Anillo Lobo",
        price:"650",
        image:"../anillos/anillo-lobo-1.webp",
        image2:"../anillos/anillo-lobo-2.webp",
    },
    {
        category:"Anillos",
        id:"10",
        title:"Anillo Runas",
        price:"650",
        image:"../anillos/anillo-runas-1.webp",
        image2:"../anillos/anillo-runas-2.webp",
        image3:"../anillos/anillo-runas-3.webp",
        image4:"../anillos/anillo-runas-4.webp",
    },
    {
        category:"Anillos",
        id:"11",
        title:"Anillo Fragua",
        price:"650",
        image:"../anillos/anillo-fragua-1.webp",
        image2:"../anillos/anillo-fragua-2.webp",
        image3:"../anillos/anillo-fragua-3.webp",
        image4:"../anillos/anillo-fragua-4.webp",
        image5:"../anillos/anillo-fragua-5.webp",
    },
    {
        category:"Anillos",
        id:"12",
        title:"Anillo Hacha Vegvisir",
        price:"650",
        image:"../anillos/anillo-hacha-vegvisir-1.webp",
        image2:"../anillos/anillo-hacha-vegvisir-2.webp",
        image3:"../anillos/anillo-hacha-vegvisir-3.webp",
    },
    {
        category:"Anillos",
        id:"13",
        title:"Anillo Casco Escandinavo",
        price:"650",
        image:"../anillos/anillo-casco-1.webp",
        image2:"../anillos/anillo-casco-2.webp",
        image3:"../anillos/anillo-casco-3.webp",
    },
    {
        category:"Anillos",
        id:"14",
        title:"Anillo Valknut",
        price:"650",
        image:"../anillos/anillo-valknut-1.webp",
        image2:"../anillos/anillo-valknut-2.webp",
    },
    {
        category:"Anillos",
        id:"15",
        title:"Anillo Mjolnir",
        price:"650",
        image:"../anillos/anillo-mjolnir-1.webp",
        image2:"../anillos/anillo-mjolnir-2.webp",
        image3:"../anillos/anillo-mjolnir-3.webp",
    },
    {
        category:"Anillos",
        id:"16",
        title:"Anillo Brujula",
        price:"650",
        image:"../anillos/anillo-rosa-vientos-1.webp",
        image2:"../anillos/anillo-rosa-vientos-2.webp",
        image3:"../anillos/anillo-rosa-vientos-3.webp",
    },
    {
        category:"Anillos",
        id:"17",
        title:"Anillo Antiguo",
        price:"650",
        image:"../anillos/anillo-antiguo-1.webp",
        image2:"../anillos/anillo-antiguo-2.webp",
        image3:"../anillos/anillo-antiguo-3.webp",
        image4:"../anillos/anillo-antiguo-4.webp",
    },
    {
        category:"Anillos",
        id:"18",
        title:"Anillo Yggdrasil",
        price:"650",
        image:"../anillos/anillo-yggdrasil-1.webp",
        image2:"../anillos/anillo-yggdrasil-2.webp",
    }
];

export default anillos;