const brazaletes = [
    {
        category:"Brazaletes",
        id:"1",
        title:"Brazalete Cuero",
        price:"650",
        image:"../brazaletes/brazalete-cuero-1.webp",
        image2:"../brazaletes/brazalete-cuero-2.webp",
        image3:"../brazaletes/brazalete-cuero-3.webp",
        image4:"../brazaletes/brazalete-cuero-4.webp",
        image5:"../brazaletes/brazalete-cuero-5.webp",
    },
    {
        category:"Brazaletes",
        id:"2",
        title:"Pulsera Dragon",
        price:"650",
        image:"../brazaletes/brazalete-dragon-1.webp",
        image2:"../brazaletes/brazalete-dragon-2.webp",
        image3:"../brazaletes/brazalete-dragon-3.webp",
        image4:"../brazaletes/brazalete-dragon-4.webp",
        image5:"../brazaletes/brazalete-dragon-5.webp",
    },
    {
        category:"Brazaletes",
        id:"3",
        title:"Bazalete Fenrir",
        price:"650",
        image:"../brazaletes/brazalete-fenrir-1.webp",
        image2:"../brazaletes/brazalete-fenrir-2.webp",
        image3:"../brazaletes/brazalete-fenrir-3.webp",
    },
    {
        category:"Brazaletes",
        id:"4",
        title:"Bazalete Flecha",
        price:"650",
        image:"../brazaletes/brazalete-flecha-1.webp",
        image2:"../brazaletes/brazalete-flecha-2.webp",
        image3:"../brazaletes/brazalete-flecha-3.webp",
        image4:"../brazaletes/brazalete-flecha-4.webp",
        image5:"../brazaletes/brazalete-flecha-5.webp",
        image6:"../brazaletes/brazalete-flecha-6.webp",
    },
    {
        category:"Brazaletes",
        id:"5",
        title:"Bazalete Hacha",
        price:"650",
        image:"../brazaletes/brazalete-hacha-1.webp",
        image2:"../brazaletes/brazalete-hacha-2.webp",
        image3:"../brazaletes/brazalete-hacha-3.webp",
        image4:"../brazaletes/brazalete-hacha-4.webp",
    },
    {
        category:"Brazaletes",
        id:"6",
        title:"Bazalete Mjolnir",
        price:"650",
        image:"../brazaletes/brazalete-mjolnir-1.webp",
        image2:"../brazaletes/brazalete-mjolnir-2.webp",
        image3:"../brazaletes/brazalete-mjolnir-3.webp",
        image4:"../brazaletes/brazalete-mjolnir-4.webp",
    },
    {
        category:"Brazaletes",
        id:"7",
        title:"Bazalete Valknut",
        price:"650",
        image:"../brazaletes/brazalete-valknut-1.webp",
        image2:"../brazaletes/brazalete-valknut-2.webp",
        image3:"../brazaletes/brazalete-valknut-3.webp",
    },
    {
        category:"Brazaletes",
        id:"8",
        title:"Pulsera Ancla",
        price:"650",
        image:"../brazaletes/pulsera-ancla-1.webp",
        image2:"../brazaletes/pulsera-ancla-2.webp",
        image3:"../brazaletes/pulsera-ancla-3.webp",
        image4:"../brazaletes/pulsera-ancla-4.webp",
    },
    {
        category:"Brazaletes",
        id:"9",
        title:"Pulsera Trenzada Cuero",
        price:"650",
        image:"../brazaletes/pulsera-cuero-doble-1.webp",
        image2:"../brazaletes/pulsera-cuero-doble-2.webp",
        image3:"../brazaletes/pulsera-cuero-doble-3.webp",
        image4:"../brazaletes/pulsera-cuero-doble-4.webp",
    },
    {
        category:"Brazaletes",
        id:"10",
        title:"Pulsera Cuero Rustica",
        price:"650",
        image:"../brazaletes/pulsera-cuero-rustica-1.webp",
        image2:"../brazaletes/pulsera-cuero-rustica-2.webp",
        image3:"../brazaletes/pulsera-cuero-rustica-3.webp",
        image4:"../brazaletes/pulsera-cuero-rustica-4.webp",
        image5:"../brazaletes/pulsera-cuero-rustica-5.webp",
        image6:"../brazaletes/pulsera-cuero-rustica-6.webp",
    },
    {
        category:"Brazaletes",
        id:"11",
        title:"Pulsera Dragon",
        price:"650",
        image:"../brazaletes/pulsera-dragon-1.webp",
        image2:"../brazaletes/pulsera-dragon-2.webp",
        image3:"../brazaletes/pulsera-dragon-3.webp",    
    },
    {
        category:"Brazaletes",
        id:"12",
        title:"Pulsera Runas",
        price:"650",
        image:"../brazaletes/pulsera-runas-1.webp",
        image2:"../brazaletes/pulsera-runas-2.webp",
        image3:"../brazaletes/pulsera-runas-3.webp",
        image4:"../brazaletes/pulsera-runas-4.webp",      
    },
];

export default brazaletes;