const colgantes = [
    {
        category:"Colgantes",
        id:"1",
        title:"Colgante Cabeza Oso Plata",
        price:"650",
        image:"../colgantes/colgante-cabeza-oso-plata-1.webp",
        image2:"../colgantes/colgante-cabeza-oso-plata-2.webp",
        image3:"../colgantes/colgante-cabeza-oso-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"2",
        title:"Colgante Fenrir Plata",
        price:"650",
        image:"../colgantes/colgante-fenrir-plata-1.webp",
        image2:"../colgantes/colgante-fenrir-plata-2.webp",
        image3:"../colgantes/colgante-fenrir-plata-3.webp",
        image4:"../colgantes/colgante-fenrir-plata-4.webp",
    },
    {
        category:"Colgantes",
        id:"3",
        title:"Colgante Hacha Plata",
        price:"650",
        image:"../colgantes/colgante-hacha-plata-1.webp",
        image2:"../colgantes/colgante-hacha-plata-2.webp",
        image3:"../colgantes/colgante-hacha-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"4",
        title:"Colgante Mjolnir Carneros Plata",
        price:"650",
        image:"../colgantes/colgante-mjolnir-carneros-plata-1.webp",
        image2:"../colgantes/colgante-mjolnir-carneros-plata-2.webp",
        image3:"../colgantes/colgante-mjolnir-carneros-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"5",
        title:"Colgante Mjolnir Plata",
        price:"650",
        image:"../../colgantes/colgante-mjolnir-plata-1.webp",
        image2:"../../colgantes/colgante-mjolnir-plata-2.webp",
        image3:"../../colgantes/colgante-mjolnir-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"6",
        title:"Colgante Punta Lanza Plata",
        price:"650",
        image:"../colgantes/colgante-punta-lanza-plata-1.webp",
        image2:"../colgantes/colgante-punta-lanza-plata-2.webp",
        image3:"../colgantes/colgante-punta-lanza-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"7",
        title:"Colgante Lobo",
        price:"650",
        image:"../colgantes/collar-lobo-1.webp",
        image2:"../colgantes/collar-lobo-2.webp",
        image3:"../colgantes/collar-lobo-3.webp",
        image4:"../colgantes/collar-lobo-4.webp",
        image5:"../colgantes/collar-lobo-5.webp",
    },
    {
        category:"Colgantes",
        id:"8",
        title:"Colgante Brújula",
        price:"650",
        image:"../colgantes/colgante-brujula-1.webp",
        image2:"../colgantes/colgante-brujula-2.webp",
        image3:"../colgantes/colgante-brujula-3.webp",
        image4:"../colgantes/colgante-brujula-4.webp",
        image5:"../colgantes/colgante-brujula-5.webp",
    },
    {
        category:"Colgantes",
        id:"9",
        title:"Colgante Garra Oso",
        price:"650",
        image:"../colgantes/colgante-garra-oso-1.webp",
        image2:"../colgantes/colgante-garra-oso-2.webp",
        image3:"../colgantes/colgante-garra-oso-3.webp",
    },
    {
        category:"Colgantes",
        id:"10",
        title:"Colgante Vegvisir",
        price:"650",
        image:"../colgantes/colgante-vegvisir-1.webp",
        image2:"../colgantes/colgante-vegvisir-2.webp",
        image3:"../colgantes/colgante-vegvisir-3.webp",
        image4:"../colgantes/colgante-vegvisir-4.webp",
    },
    {
        category:"Colgantes",
        id:"11",
        title:"Colgante Mjolnir",
        price:"650",
        image:"../colgantes/colgante-mjolnir-1.webp",
        image2:"../colgantes/colgante-mjolnir-2.webp",
        image3:"../colgantes/colgante-mjolnir-3.webp",
        image4:"../colgantes/colgante-mjolnir-4.webp",
    },
    {
        category:"Colgantes",
        id:"12",
        title:"Colgante Odin",
        price:"650",
        image:"../colgantes/colgante-odin-1.webp",
        image2:"../colgantes/colgante-odin-2.webp",
        image3:"../colgantes/colgante-odin-3.webp",
    },
    {
        category:"Colgantes",
        id:"13",
        title:"Colgante Hacha Berserker",
        price:"650",
        image:"../colgantes/collar-hacha-1.webp",
        image2:"../colgantes/collar-hacha-2.webp",
        image3:"../colgantes/collar-hacha-3.webp",
    },
    {
        category:"Colgantes",
        id:"14",
        title:"Colgante Cruz Celta",
        price:"650",
        image:"../colgantes/collar-cruz-celta-1.webp",
        image2:"../colgantes/collar-cruz-celta-2.webp",
    },
    {
        category:"Colgantes",
        id:"15",
        title:"Colgante Valknut",
        price:"650",
        image:"../colgantes/colgante-valknut-1.webp",
        image2:"../colgantes/colgante-valknut-2.webp",
        image3:"../colgantes/colgante-valknut-3.webp",
        image4:"../colgantes/colgante-valknut-4.webp",
    },
    {
        category:"Colgantes",
        id:"16",
        title:"Colgante Escudo Hacha",
        price:"650",
        image:"../colgantes/colgante-escudo-hacha-1.webp",
        image2:"../colgantes/colgante-escudo-hacha-2.webp",
        image3:"../colgantes/colgante-escudo-hacha-3.webp",
        image4:"../colgantes/colgante-escudo-hacha-4.webp",
    },
    {
        category:"Colgantes",
        id:"17",
        title:"Colgante Yggdrasil Ying Yang",
        price:"650",
        image:"../colgantes/collar-yggdrasil-ying-yang-1.webp",
        image2:"../colgantes/collar-yggdrasil-ying-yang-2.webp",
        image3:"../colgantes/collar-yggdrasil-ying-yang-3.webp",
    },
    {
        category:"Colgantes",
        id:"18",
        title:"Colgante Triqueta",
        price:"650",
        image:"../colgantes/collar-triqueta-1.webp",
        image2:"../colgantes/collar-triqueta-2.webp",
        image3:"../colgantes/collar-triqueta-3.webp",
        image4:"../colgantes/collar-triqueta-4.webp",
    },
    {
        category:"Colgantes",
        id:"19",
        title:"Colgante Simbolos",
        price:"650",
        image:"../colgantes/colgante-simbolos-1.webp",
        image2:"../colgantes/colgante-simbolos-2.webp",
        image3:"../colgantes/colgante-simbolos-3.webp",
    },
    {
        category:"Colgantes",
        id:"20",
        title:"Colgante Cuervos Volando",
        price:"650",
        image:"../colgantes/colgante-cuervos-1.webp",
        image2:"../colgantes/colgante-cuervos-2.webp",
        image3:"../colgantes/colgante-cuervos-3.webp",
        image4:"../colgantes/colgante-cuervos-4.webp",
    },
    {
        category:"Colgantes",
        id:"21",
        title:"Colgante Obsidiana Lobo",
        price:"650",
        image:"../colgantes/collar-obsidiana-lobo-1.webp",
        image2:"../colgantes/collar-obsidiana-lobo-2.webp",
        image3:"../colgantes/collar-obsidiana-lobo-3.webp",
        image4:"../colgantes/collar-obsidiana-lobo-4.webp",
    },
    {
        category:"Colgantes",
        id:"22",
        title:"Colgante Cabeza Lobo",
        price:"650",
        image:"../colgantes/colgante-lobo-1.webp",
        image2:"../colgantes/colgante-lobo-2.webp",
        image3:"../colgantes/colgante-lobo-3.webp",
        image4:"../colgantes/colgante-lobo-4.webp",
        image5:"../colgantes/colgante-lobo-5.webp",
    },
    {
        category:"Colgantes",
        id:"23",
        title:"Colgante Diente Lobo",
        price:"650",
        image:"../colgantes/collar-diente-lobo-1.webp",
        image2:"../colgantes/collar-diente-lobo-2.webp",
        image3:"../colgantes/collar-diente-lobo-3.webp",
        image4:"../colgantes/collar-diente-lobo-4.webp",
        image5:"../colgantes/collar-diente-lobo-5.webp",
    },
    {
        category:"Colgantes",
        id:"24",
        title:"Colgante Lobos Yggdrasil",
        price:"650",
        image:"../colgantes/collar-lobos-yggdrasil-1.webp",
        image2:"../colgantes/collar-lobos-yggdrasil-2.webp",
        image3:"../colgantes/collar-lobos-yggdrasil-3.webp",
        image4:"../colgantes/collar-lobos-yggdrasil-4.webp",
    },
];

export default colgantes;