const ProductsMock = [
    {
        category:"Colgantes",
        id:"1",
        title:"Colgante Cabeza Oso Plata",
        price:"650",
        image:"../colgantes/colgante-cabeza-oso-plata-1.webp",
        image2:"../colgantes/colgante-cabeza-oso-plata-2.webp",
        image3:"../colgantes/colgante-cabeza-oso-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"2",
        title:"Colgante Fenrir Plata",
        price:"650",
        image:"../colgantes/colgante-fenrir-plata-1.webp",
        image2:"../colgantes/colgante-fenrir-plata-2.webp",
        image3:"../colgantes/colgante-fenrir-plata-3.webp",
        image4:"../colgantes/colgante-fenrir-plata-4.webp",
    },
    {
        category:"Colgantes",
        id:"3",
        title:"Colgante Hacha Plata",
        price:"650",
        image:"../colgantes/colgante-hacha-plata-1.webp",
        image2:"../colgantes/colgante-hacha-plata-2.webp",
        image3:"../colgantes/colgante-hacha-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"4",
        title:"Colgante Mjolnir Carneros Plata",
        price:"650",
        image:"../colgantes/colgante-mjolnir-carneros-plata-1.webp",
        image2:"../colgantes/colgante-mjolnir-carneros-plata-2.webp",
        image3:"../colgantes/colgante-mjolnir-carneros-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"5",
        title:"Colgante Mjolnir Plata",
        price:"650",
        image:"../../colgantes/colgante-mjolnir-plata-1.webp",
        image2:"../../colgantes/colgante-mjolnir-plata-2.webp",
        image3:"../../colgantes/colgante-mjolnir-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"6",
        title:"Colgante Punta Lanza Plata",
        price:"650",
        image:"../colgantes/colgante-punta-lanza-plata-1.webp",
        image2:"../colgantes/colgante-punta-lanza-plata-2.webp",
        image3:"../colgantes/colgante-punta-lanza-plata-3.webp",
    },
    {
        category:"Colgantes",
        id:"7",
        title:"Colgante Lobo",
        price:"650",
        image:"../colgantes/collar-lobo-1.webp",
        image2:"../colgantes/collar-lobo-2.webp",
        image3:"../colgantes/collar-lobo-3.webp",
        image4:"../colgantes/collar-lobo-4.webp",
        image5:"../colgantes/collar-lobo-5.webp",
    },
    {
        category:"Colgantes",
        id:"8",
        title:"Colgante Brújula",
        price:"650",
        image:"../colgantes/colgante-brujula-1.webp",
        image2:"../colgantes/colgante-brujula-2.webp",
        image3:"../colgantes/colgante-brujula-3.webp",
        image4:"../colgantes/colgante-brujula-4.webp",
        image5:"../colgantes/colgante-brujula-5.webp",
    },
    {
        category:"Colgantes",
        id:"9",
        title:"Colgante Garra Oso",
        price:"650",
        image:"../colgantes/colgante-garra-oso-1.webp",
        image2:"../colgantes/colgante-garra-oso-2.webp",
        image3:"../colgantes/colgante-garra-oso-3.webp",
    },
    {
        category:"Colgantes",
        id:"10",
        title:"Colgante Vegvisir",
        price:"650",
        image:"../colgantes/colgante-vegvisir-1.webp",
        image2:"../colgantes/colgante-vegvisir-2.webp",
        image3:"../colgantes/colgante-vegvisir-3.webp",
        image4:"../colgantes/colgante-vegvisir-4.webp",
    },
    {
        category:"Colgantes",
        id:"11",
        title:"Colgante Mjolnir",
        price:"650",
        image:"../colgantes/colgante-mjolnir-1.webp",
        image2:"../colgantes/colgante-mjolnir-2.webp",
        image3:"../colgantes/colgante-mjolnir-3.webp",
        image4:"../colgantes/colgante-mjolnir-4.webp",
    },
    {
        category:"Colgantes",
        id:"12",
        title:"Colgante Odin",
        price:"650",
        image:"../colgantes/colgante-odin-1.webp",
        image2:"../colgantes/colgante-odin-2.webp",
        image3:"../colgantes/colgante-odin-3.webp",
    },
    {
        category:"Colgantes",
        id:"13",
        title:"Colgante Hacha Berserker",
        price:"650",
        image:"../colgantes/collar-hacha-1.webp",
        image2:"../colgantes/collar-hacha-2.webp",
        image3:"../colgantes/collar-hacha-3.webp",
    },
    {
        category:"Colgantes",
        id:"14",
        title:"Colgante Cruz Celta",
        price:"650",
        image:"../colgantes/collar-cruz-celta-1.webp",
        image2:"../colgantes/collar-cruz-celta-2.webp",
    },
    {
        category:"Colgantes",
        id:"15",
        title:"Colgante Valknut",
        price:"650",
        image:"../colgantes/colgante-valknut-1.webp",
        image2:"../colgantes/colgante-valknut-2.webp",
        image3:"../colgantes/colgante-valknut-3.webp",
        image4:"../colgantes/colgante-valknut-4.webp",
    },
    {
        category:"Colgantes",
        id:"16",
        title:"Colgante Escudo Hacha",
        price:"650",
        image:"../colgantes/colgante-escudo-hacha-1.webp",
        image2:"../colgantes/colgante-escudo-hacha-2.webp",
        image3:"../colgantes/colgante-escudo-hacha-3.webp",
        image4:"../colgantes/colgante-escudo-hacha-4.webp",
    },
    {
        category:"Colgantes",
        id:"17",
        title:"Colgante Yggdrasil Ying Yang",
        price:"650",
        image:"../colgantes/collar-yggdrasil-ying-yang-1.webp",
        image2:"../colgantes/collar-yggdrasil-ying-yang-2.webp",
        image3:"../colgantes/collar-yggdrasil-ying-yang-3.webp",
    },
    {
        category:"Colgantes",
        id:"18",
        title:"Colgante Triqueta",
        price:"650",
        image:"../colgantes/collar-triqueta-1.webp",
        image2:"../colgantes/collar-triqueta-2.webp",
        image3:"../colgantes/collar-triqueta-3.webp",
        image4:"../colgantes/collar-triqueta-4.webp",
    },
    {
        category:"Colgantes",
        id:"19",
        title:"Colgante Simbolos",
        price:"650",
        image:"../colgantes/colgante-simbolos-1.webp",
        image2:"../colgantes/colgante-simbolos-2.webp",
        image3:"../colgantes/colgante-simbolos-3.webp",
    },
    {
        category:"Colgantes",
        id:"20",
        title:"Colgante Cuervos Volando",
        price:"650",
        image:"../colgantes/colgante-cuervos-1.webp",
        image2:"../colgantes/colgante-cuervos-2.webp",
        image3:"../colgantes/colgante-cuervos-3.webp",
        image4:"../colgantes/colgante-cuervos-4.webp",
    },
    {
        category:"Colgantes",
        id:"21",
        title:"Colgante Obsidiana Lobo",
        price:"650",
        image:"../colgantes/collar-obsidiana-lobo-1.webp",
        image2:"../colgantes/collar-obsidiana-lobo-2.webp",
        image3:"../colgantes/collar-obsidiana-lobo-3.webp",
        image4:"../colgantes/collar-obsidiana-lobo-4.webp",
    },
    {
        category:"Colgantes",
        id:"22",
        title:"Colgante Cabeza Lobo",
        price:"650",
        image:"../colgantes/colgante-lobo-1.webp",
        image2:"../colgantes/colgante-lobo-2.webp",
        image3:"../colgantes/colgante-lobo-3.webp",
        image4:"../colgantes/colgante-lobo-4.webp",
        image5:"../colgantes/colgante-lobo-5.webp",
    },
    {
        category:"Colgantes",
        id:"23",
        title:"Colgante Diente Lobo",
        price:"650",
        image:"../colgantes/collar-diente-lobo-1.webp",
        image2:"../colgantes/collar-diente-lobo-2.webp",
        image3:"../colgantes/collar-diente-lobo-3.webp",
        image4:"../colgantes/collar-diente-lobo-4.webp",
        image5:"../colgantes/collar-diente-lobo-5.webp",
    },
    {
        category:"Colgantes",
        id:"24",
        title:"Colgante Lobos Yggdrasil",
        price:"650",
        image:"../colgantes/collar-lobos-yggdrasil-1.webp",
        image2:"../colgantes/collar-lobos-yggdrasil-2.webp",
        image3:"../colgantes/collar-lobos-yggdrasil-3.webp",
        image4:"../colgantes/collar-lobos-yggdrasil-4.webp",
    },
    {
        category:"Anillos",
        id:"25",
        title:"Anillo Brujula Vikinga",
        price:"650",
        image:"../anillos/anillo-brujula-vikinga-1.webp",
        image2:"../anillos/anillo-brujula-vikinga-2.webp",
    },
    {
        category:"Anillos",
        id:"26",
        title:"Anillo Garra Oso",
        price:"650",
        image:"../anillos/anillo-oso-1.webp",
        image2:"../anillos/anillo-oso-2.webp",
        image3:"../anillos/anillo-oso-3.webp",
    },
    {
        category:"Anillos",
        id:"27",
        title:"Anillo Vegvisir",
        price:"650",
        image:"../anillos/anillo-vegvisir-1.webp",
        image2:"../anillos/anillo-vegvisir-2.webp",
        image3:"../anillos/anillo-vegvisir-3.webp",
    },
    {
        category:"Anillos",
        id:"28",
        title:"Anillo Runas Slim",
        price:"650",
        image:"../anillos/anillo-runas-slim-1.webp",
        image2:"../anillos/anillo-runas-slim-2.webp",
        image3:"../anillos/anillo-runas-slim-3.webp",
        image4:"../anillos/anillo-runas-slim-4.webp",
    },
    {
        category:"Anillos",
        id:"29",
        title:"Anillo Casco Loki",
        price:"650",
        image:"../anillos/anillo-casco-loki-1.webp",
        image2:"../anillos/anillo-casco-loki-2.webp",
        image3:"../anillos/anillo-casco-loki-3.webp",
        image4:"../anillos/anillo-casco-loki-4.webp",
    },
    {
        category:"Anillos",
        id:"30",
        title:"Anillo Craneo Cabra",
        price:"650",
        image:"../anillos/anillo-craneo-cabra-1.webp",
        image2:"../anillos/anillo-craneo-cabra-2.webp",
        image3:"../anillos/anillo-craneo-cabra-3.webp",
        image4:"../anillos/anillo-craneo-cabra-4.webp",
        image5:"../anillos/anillo-craneo-cabra-5.webp",
    },
    {
        category:"Anillos",
        id:"31",
        title:"Anillo Fenrir",
        price:"650",
        image:"../anillos/anillo-fenrir-1.webp",
        image2:"../anillos/anillo-fenrir-2.webp",
        image3:"../anillos/anillo-fenrir-3.webp",
    },
    {
        category:"Anillos",
        id:"32",
        title:"Anillo Hugin & Munin",
        price:"650",
        image:"../anillos/anillo-hugin-munin-1.webp",
        image2:"../anillos/anillo-hugin-munin-2.webp",
        image3:"../anillos/anillo-hugin-munin-3.webp",
    },
    {
        category:"Anillos",
        id:"33",
        title:"Anillo Lobo",
        price:"650",
        image:"../anillos/anillo-lobo-1.webp",
        image2:"../anillos/anillo-lobo-2.webp",
    },
    {
        category:"Anillos",
        id:"34",
        title:"Anillo Runas",
        price:"650",
        image:"../anillos/anillo-runas-1.webp",
        image2:"../anillos/anillo-runas-2.webp",
        image3:"../anillos/anillo-runas-3.webp",
        image4:"../anillos/anillo-runas-4.webp",
    },
    {
        category:"Anillos",
        id:"35",
        title:"Anillo Fragua",
        price:"650",
        image:"../anillos/anillo-fragua-1.webp",
        image2:"../anillos/anillo-fragua-2.webp",
        image3:"../anillos/anillo-fragua-3.webp",
        image4:"../anillos/anillo-fragua-4.webp",
        image5:"../anillos/anillo-fragua-5.webp",
    },
    {
        category:"Anillos",
        id:"36",
        title:"Anillo Hacha Vegvisir",
        price:"650",
        image:"../anillos/anillo-hacha-vegvisir-1.webp",
        image2:"../anillos/anillo-hacha-vegvisir-2.webp",
        image3:"../anillos/anillo-hacha-vegvisir-3.webp",
    },
    {
        category:"Anillos",
        id:"37",
        title:"Anillo Casco Escandinavo",
        price:"650",
        image:"../anillos/anillo-casco-1.webp",
        image2:"../anillos/anillo-casco-2.webp",
        image3:"../anillos/anillo-casco-3.webp",
    },
    {
        category:"Anillos",
        id:"38",
        title:"Anillo Valknut",
        price:"650",
        image:"../anillos/anillo-valknut-1.webp",
        image2:"../anillos/anillo-valknut-2.webp",
    },
    {
        category:"Anillos",
        id:"39",
        title:"Anillo Mjolnir",
        price:"650",
        image:"../anillos/anillo-mjolnir-1.webp",
        image2:"../anillos/anillo-mjolnir-2.webp",
        image3:"../anillos/anillo-mjolnir-3.webp",
    },
    {
        category:"Anillos",
        id:"40",
        title:"Anillo Brujula",
        price:"650",
        image:"../anillos/anillo-rosa-vientos-1.webp",
        image2:"../anillos/anillo-rosa-vientos-2.webp",
        image3:"../anillos/anillo-rosa-vientos-3.webp",
    },
    {
        category:"Anillos",
        id:"41",
        title:"Anillo Antiguo",
        price:"650",
        image:"../anillos/anillo-antiguo-1.webp",
        image2:"../anillos/anillo-antiguo-2.webp",
        image3:"../anillos/anillo-antiguo-3.webp",
        image4:"../anillos/anillo-antiguo-4.webp",
    },
    {
        category:"Anillos",
        id:"42",
        title:"Anillo Yggdrasil",
        price:"650",
        image:"../anillos/anillo-yggdrasil-1.webp",
        image2:"../anillos/anillo-yggdrasil-2.webp",
    },
    {
        category:"Brazaletes",
        id:"43",
        title:"Brazalete Cuero",
        price:"650",
        image:"../brazaletes/brazalete-cuero-1.webp",
        image2:"../brazaletes/brazalete-cuero-2.webp",
        image3:"../brazaletes/brazalete-cuero-3.webp",
        image4:"../brazaletes/brazalete-cuero-4.webp",
        image5:"../brazaletes/brazalete-cuero-5.webp",
    },
    {
        category:"Brazaletes",
        id:"44",
        title:"Pulsera Dragon",
        price:"650",
        image:"../brazaletes/brazalete-dragon-1.webp",
        image2:"../brazaletes/brazalete-dragon-2.webp",
        image3:"../brazaletes/brazalete-dragon-3.webp",
        image4:"../brazaletes/brazalete-dragon-4.webp",
        image5:"../brazaletes/brazalete-dragon-5.webp",
    },
    {
        category:"Brazaletes",
        id:"45",
        title:"Bazalete Fenrir",
        price:"650",
        image:"../brazaletes/brazalete-fenrir-1.webp",
        image2:"../brazaletes/brazalete-fenrir-2.webp",
        image3:"../brazaletes/brazalete-fenrir-3.webp",
    },
    {
        category:"Brazaletes",
        id:"46",
        title:"Bazalete Flecha",
        price:"650",
        image:"../brazaletes/brazalete-flecha-1.webp",
        image2:"../brazaletes/brazalete-flecha-2.webp",
        image3:"../brazaletes/brazalete-flecha-3.webp",
        image4:"../brazaletes/brazalete-flecha-4.webp",
        image5:"../brazaletes/brazalete-flecha-5.webp",
        image6:"../brazaletes/brazalete-flecha-6.webp",
    },
    {
        category:"Brazaletes",
        id:"47",
        title:"Bazalete Hacha",
        price:"650",
        image:"../brazaletes/brazalete-hacha-1.webp",
        image2:"../brazaletes/brazalete-hacha-2.webp",
        image3:"../brazaletes/brazalete-hacha-3.webp",
        image4:"../brazaletes/brazalete-hacha-4.webp",
    },
    {
        category:"Brazaletes",
        id:"48",
        title:"Bazalete Mjolnir",
        price:"650",
        image:"../brazaletes/brazalete-mjolnir-1.webp",
        image2:"../brazaletes/brazalete-mjolnir-2.webp",
        image3:"../brazaletes/brazalete-mjolnir-3.webp",
        image4:"../brazaletes/brazalete-mjolnir-4.webp",
    },
    {
        category:"Brazaletes",
        id:"49",
        title:"Bazalete Valknut",
        price:"650",
        image:"../brazaletes/brazalete-valknut-1.webp",
        image2:"../brazaletes/brazalete-valknut-2.webp",
        image3:"../brazaletes/brazalete-valknut-3.webp",
    },
    {
        category:"Brazaletes",
        id:"50",
        title:"Pulsera Ancla",
        price:"650",
        image:"../brazaletes/pulsera-ancla-1.webp",
        image2:"../brazaletes/pulsera-ancla-2.webp",
        image3:"../brazaletes/pulsera-ancla-3.webp",
        image4:"../brazaletes/pulsera-ancla-4.webp",
    },
    {
        category:"Brazaletes",
        id:"51",
        title:"Pulsera Trenzada Cuero",
        price:"650",
        image:"../brazaletes/pulsera-cuero-doble-1.webp",
        image2:"../brazaletes/pulsera-cuero-doble-2.webp",
        image3:"../brazaletes/pulsera-cuero-doble-3.webp",
        image4:"../brazaletes/pulsera-cuero-doble-4.webp",
    },
    {
        category:"Brazaletes",
        id:"52",
        title:"Pulsera Cuero Rustica",
        price:"650",
        image:"../brazaletes/pulsera-cuero-rustica-1.webp",
        image2:"../brazaletes/pulsera-cuero-rustica-2.webp",
        image3:"../brazaletes/pulsera-cuero-rustica-3.webp",
        image4:"../brazaletes/pulsera-cuero-rustica-4.webp",
        image5:"../brazaletes/pulsera-cuero-rustica-5.webp",
        image6:"../brazaletes/pulsera-cuero-rustica-6.webp",
    },
    {
        category:"Brazaletes",
        id:"53",
        title:"Pulsera Dragon",
        price:"650",
        image:"../brazaletes/pulsera-dragon-1.webp",
        image2:"../brazaletes/pulsera-dragon-2.webp",
        image3:"../brazaletes/pulsera-dragon-3.webp",    
    },
    {
        category:"Brazaletes",
        id:"54",
        title:"Pulsera Runas",
        price:"650",
        image:"../brazaletes/pulsera-runas-1.webp",
        image2:"../brazaletes/pulsera-runas-2.webp",
        image3:"../brazaletes/pulsera-runas-3.webp",
        image4:"../brazaletes/pulsera-runas-4.webp",      
    },
];

export default ProductsMock;